apiVersion: v1
kind: ConfigMap
metadata:
  name: cic-configmap
  namespace: default
data:
   LOGLEVEL: 'debug'
   NS_PROTOCOL: 'http'
   NS_PORT: '80'
   NS_HTTP2_SERVER_SIDE: 'ON'
   NS_ANALYTICS_CONFIG: |
     distributed_tracing:
       enable: 'false'
       samplingrate: 100
     endpoint:
       server: '10.106.192.145'
     timeseries: 
       port: 5563 
       metrics:
         enable: 'true'
         mode: 'avro' 
       auditlogs:
         enable: 'false'
       events: 
         enable: 'false'
     transactions:
       enable: 'false'
       port: 5557