apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sales-portal
  annotations:
   ingress.citrix.com/insecure-termination: "allow"
   kubernetes.io/ingress.class: "sales-portal"
   ingress.citrix.com/analyticsprofile: '{"webinsight": {"httpurl":"ENABLED", "httpuseragent":"ENABLED", "httphost":"ENABLED", "httpmethod":"ENABLED", "httpcontenttype":"ENABLED"}, "tcpinsight": {"tcpBurstReporting":"DISABLED"}}'
spec:
      tls:
      - hosts:
      rules:
       - host: sales-portal
         http:
          paths:
          - path:
            backend:
              serviceName: sales-portal-service 
              servicePort: 5000
       - host: leads
         http:
          paths:
          - path:
            backend:
              serviceName: leads-service
              servicePort: 5000
       - host: opportunities
         http:
          paths:
          - path:
            backend:
              serviceName: opportunities-service
              servicePort: 5000
       - host: product-catalogue
         http:
          paths:
          - path:
            backend:
              serviceName: product-catalogue-service
              servicePort: 5000
       - host: catalogue-store
         http:
          paths:
          - path: 
            backend:
              serviceName: catalogue-store-service
              servicePort: 5000
       - host: accounts
         http:
          paths:
          - path: 
            backend:
              serviceName: accounts-service
              servicePort: 5000
       - host: payables
         http:
          paths:
          - path: 
            backend:
              serviceName: payables-service
              servicePort: 5000
       - host: receivables
         http:
          paths: 
          - path:
            backend:
              serviceName: receivables-service
              servicePort: 5000
